### ISSUE TITLE
Commit-hash of the binaries does not match the tag or any commit on github.

### ISSUE THREAD

**Issue by fdoving** [AvianNetwork/Avian#12]
Commit-hash of the binaries does not match the tag or any commit on github.
This suggests the binaries are built from a commit not published to github.

![image](https://user-images.githubusercontent.com/26197922/146045983-768eafa8-975b-45b8-ad58-5058673871dd.png)

Windows and Linux tested.

**Comment by alamshafil** [comment]
I didn't upload the binaries for v3.1.0 but I think the cause of this is the person who uploaded the binaries got them an commit before they were squashed (causing a force-push on GH). I'll make sure this doesn't happen for the v3.1.1 release. Thank you for bringing this to light.
