### ISSUE TITLE
I update wallet from 3 to 3.1 and my balance is 0 now

### ISSUE THREAD

**Issue by acrata29** [AvianNetwork/Avian#13]
I mined AVN a few days ago. My balance was 18451 in wallet (3.0). Waiting for more payments from mining and the wallet at one point didn't update the network. I saw the new version of the wallet and I downloaded it.

I updated the wallet and all looks ok while updating the network. But when the wallet finished, only was the first transaction and my balance is 0. The other payments are not there and the balance not update. Worse still is at 0. 

[Transaction](https://ibb.co/J3Bsmjf)
[Balance](https://ibb.co/YjJPPmd)

Please help me

**Comment by alamshafil** [comment]
Can you make sure your Avian 3.1.0 is reading the correct `wallet.dat` which contained `18451` coins?
Additionally it would be helpful if you could send your wallet address and/or transaction IDs. I recommend you join our Discord server to create a private ticket so you can send your address and TX ID.

It could be possible you have mined coins before our rollback which may have caused your transactions to be erased. The TX ID will be helpful in verifying if this is the case.

**Comment by acrata29** [comment]
Resolved ;)
