### ISSUE TITLE
Fix datadir

### ISSUE THREAD

**Issue by alamshafil** [AvianNetwork/Avian#4]
Datadir still points to `RavenLite` should be fixed in #2

**Comment by JABirchall** [comment]
Most other crypto wallets let you choose the data dir on first launch, could this be added to Avn

**Comment by alamshafil** [comment]
The wallet already does this when you open it for the first time :) Also this already has been fixed.

**Comment by taperj** [comment]
If needed, you can also trigger this behavior at any wallet start by appending `-choosedatadir` to your startup command.
