### ISSUE TITLE
solo mining by wallet (daemon)

### ISSUE THREAD

**Issue by imhajes** [AvianNetwork/Avian#56]
how can i mining avn on ubuntu (SOLO) without pool server in the daemon localy in the ubuntu terminal - or how can used `avian-cli` or `aviand` on terminal for mining

**Comment by alamshafil** [comment]
First you would need to setup `aviand` server.

1. Create conf file in `~/.avian/avian.conf`
```
server=1
listen=1
rpcuser=<put username here>
rpcpassword=<put password here>
```
2. Start `aviand` by type
```
chmod +x aviand avian-cli
./aviand
```
3. Use avian-cli
```
./avian-cli help
```
If you output that means your `aviand` server is working.


**Option 1: Solo Mining via RPC **
Type this:
```
./avian-cli setgenerate true -1
```
Using `-1` will use all of your CPU cores.

**Option 2: Using mining software that support RPC (more cpu efficent)**
Install the miner and use the given username and password. The default port for AVN is `7896`.

I will close the comment, if anymore help is needed then make a new issue or use Discord to make a ticket.
