### ISSUE TITLE
QT: Odd-looking scrollbars 

### ISSUE THREAD

**Issue by alamshafil** [AvianNetwork/Avian#82]
Scroll bar in UI looks odd and old, please comment if you see the same thing. If this issue is present on all platforms, we can update this design. 

Running Avian 4.0.0 on Arch Linux x86_64 (GNOME on Wayland)
![Screenshot from 2022-07-13 00-13-42](https://user-images.githubusercontent.com/36016500/178649882-191f9294-385a-4c32-9cc7-d1c26fed078d.png)

**Comment by cdonnachie** [comment]
Scroll bars are using default OS rendering, if we do change in CSS to alter the appearance it cannot be done for MacOS build as they will not work.  Just need to keep that in mind when testing any alteration.

**Comment by alamshafil** [comment]
That's useful to know; however, my QT theme's scrollbars do not look like that. I'm going to try removing all `QScrollBar` styling and see if that affects anything. Thanks for help!

**Comment by alamshafil** [comment]
Closing since Windows is not effected.
